"""Add features, feature_compositions, feature_metrics tables

Revision ID: 06436f5dd963
Revises: 
Create Date: 2025-04-20 20:40:01.697030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06436f5dd963'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('price_correlation', sa.Float(), nullable=True),
    sa.Column('returns_correlation', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_composition_id', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('price_correlation', sa.Float(), nullable=True),
    sa.Column('returns_correlation', sa.Float(), nullable=True),
    sa.Column('mutual_info_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feature_composition_id'], ['feature_compositions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dji_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dji_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('dji_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('dji_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('dji_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('dji_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('dji_prices_symbol_date_key', 'dji_prices', type_='unique')
    op.create_index(op.f('ix_dji_prices_date'), 'dji_prices', ['date'], unique=False)
    op.drop_index('idx_fred_consumer_business_date', table_name='fred_consumer_business')
    op.create_index(op.f('ix_fred_consumer_business_date'), 'fred_consumer_business', ['date'], unique=False)
    op.drop_index('idx_fred_economic_growth_date', table_name='fred_economic_growth')
    op.create_index(op.f('ix_fred_economic_growth_date'), 'fred_economic_growth', ['date'], unique=False)
    op.drop_index('idx_fred_employment_date', table_name='fred_employment')
    op.create_index(op.f('ix_fred_employment_date'), 'fred_employment', ['date'], unique=False)
    op.drop_index('idx_fred_housing_date', table_name='fred_housing')
    op.create_index(op.f('ix_fred_housing_date'), 'fred_housing', ['date'], unique=False)
    op.drop_index('idx_fred_inflation_date', table_name='fred_inflation')
    op.create_index(op.f('ix_fred_inflation_date'), 'fred_inflation', ['date'], unique=False)
    op.drop_index('idx_fred_interest_rates_date', table_name='fred_interest_rates')
    op.create_index(op.f('ix_fred_interest_rates_date'), 'fred_interest_rates', ['date'], unique=False)
    op.drop_index('idx_fred_money_credit_date', table_name='fred_money_credit')
    op.create_index(op.f('ix_fred_money_credit_date'), 'fred_money_credit', ['date'], unique=False)
    op.alter_column('fred_series_metadata', 'frequency',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_index('idx_ml_backtest_results_symbol', table_name='ml_backtest_results')
    op.create_index(op.f('ix_ml_backtest_results_id'), 'ml_backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_ml_backtest_results_symbol'), 'ml_backtest_results', ['symbol'], unique=False)
    op.create_index(op.f('ix_ml_ensemble_models_id'), 'ml_ensemble_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_feature_importance_id'), 'ml_feature_importance', ['id'], unique=False)
    op.drop_index('idx_ml_model_results_symbol', table_name='ml_model_results')
    op.create_index(op.f('ix_ml_model_results_id'), 'ml_model_results', ['id'], unique=False)
    op.create_index(op.f('ix_ml_model_results_symbol'), 'ml_model_results', ['symbol'], unique=False)
    op.alter_column('ndx_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('ndx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('ndx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('ndx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('ndx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('ndx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('ndx_prices_symbol_date_key', 'ndx_prices', type_='unique')
    op.create_index(op.f('ix_ndx_prices_date'), 'ndx_prices', ['date'], unique=False)
    op.alter_column('osx_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('osx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('osx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('osx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('osx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('osx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('osx_prices_symbol_date_key', 'osx_prices', type_='unique')
    op.create_index(op.f('ix_osx_prices_date'), 'osx_prices', ['date'], unique=False)
    op.alter_column('rut_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('rut_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rut_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rut_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rut_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rut_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('rut_prices_symbol_date_key', 'rut_prices', type_='unique')
    op.create_index(op.f('ix_rut_prices_date'), 'rut_prices', ['date'], unique=False)
    op.alter_column('sox_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sox_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('sox_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('sox_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('sox_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('sox_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('sox_prices_symbol_date_key', 'sox_prices', type_='unique')
    op.create_index(op.f('ix_sox_prices_date'), 'sox_prices', ['date'], unique=False)
    op.alter_column('spx_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('spx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('spx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('spx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('spx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('spx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('spx_prices_symbol_date_key', 'spx_prices', type_='unique')
    op.create_index(op.f('ix_spx_prices_date'), 'spx_prices', ['date'], unique=False)
    op.drop_index('idx_stock_prices_date', table_name='stock_prices')
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.alter_column('treasury_yields', 'mo1',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo2',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo3',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo6',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr1',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr2',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr5',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr10',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr30',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_treasury_yields_date'), 'treasury_yields', ['date'], unique=False)
    op.alter_column('vix_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('vix_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('vix_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('vix_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('vix_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('vix_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('vix_prices_symbol_date_key', 'vix_prices', type_='unique')
    op.create_index(op.f('ix_vix_prices_date'), 'vix_prices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vix_prices_date'), table_name='vix_prices')
    op.create_unique_constraint('vix_prices_symbol_date_key', 'vix_prices', ['symbol', 'date'])
    op.alter_column('vix_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('vix_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('vix_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('vix_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('vix_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('vix_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_treasury_yields_date'), table_name='treasury_yields')
    op.alter_column('treasury_yields', 'yr30',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr10',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr5',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr2',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'yr1',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo6',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo3',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo2',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('treasury_yields', 'mo1',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.create_index('idx_stock_prices_date', 'stock_prices', ['date'], unique=False)
    op.drop_index(op.f('ix_spx_prices_date'), table_name='spx_prices')
    op.create_unique_constraint('spx_prices_symbol_date_key', 'spx_prices', ['symbol', 'date'])
    op.alter_column('spx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('spx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('spx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('spx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('spx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('spx_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_sox_prices_date'), table_name='sox_prices')
    op.create_unique_constraint('sox_prices_symbol_date_key', 'sox_prices', ['symbol', 'date'])
    op.alter_column('sox_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sox_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('sox_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('sox_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('sox_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('sox_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_rut_prices_date'), table_name='rut_prices')
    op.create_unique_constraint('rut_prices_symbol_date_key', 'rut_prices', ['symbol', 'date'])
    op.alter_column('rut_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('rut_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('rut_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('rut_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('rut_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('rut_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_osx_prices_date'), table_name='osx_prices')
    op.create_unique_constraint('osx_prices_symbol_date_key', 'osx_prices', ['symbol', 'date'])
    op.alter_column('osx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('osx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('osx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('osx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('osx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('osx_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_ndx_prices_date'), table_name='ndx_prices')
    op.create_unique_constraint('ndx_prices_symbol_date_key', 'ndx_prices', ['symbol', 'date'])
    op.alter_column('ndx_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('ndx_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('ndx_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('ndx_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('ndx_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('ndx_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_ml_model_results_symbol'), table_name='ml_model_results')
    op.drop_index(op.f('ix_ml_model_results_id'), table_name='ml_model_results')
    op.create_index('idx_ml_model_results_symbol', 'ml_model_results', ['symbol'], unique=False)
    op.drop_index(op.f('ix_ml_feature_importance_id'), table_name='ml_feature_importance')
    op.drop_index(op.f('ix_ml_ensemble_models_id'), table_name='ml_ensemble_models')
    op.drop_index(op.f('ix_ml_backtest_results_symbol'), table_name='ml_backtest_results')
    op.drop_index(op.f('ix_ml_backtest_results_id'), table_name='ml_backtest_results')
    op.create_index('idx_ml_backtest_results_symbol', 'ml_backtest_results', ['symbol'], unique=False)
    op.alter_column('fred_series_metadata', 'frequency',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_index(op.f('ix_fred_money_credit_date'), table_name='fred_money_credit')
    op.create_index('idx_fred_money_credit_date', 'fred_money_credit', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_interest_rates_date'), table_name='fred_interest_rates')
    op.create_index('idx_fred_interest_rates_date', 'fred_interest_rates', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_inflation_date'), table_name='fred_inflation')
    op.create_index('idx_fred_inflation_date', 'fred_inflation', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_housing_date'), table_name='fred_housing')
    op.create_index('idx_fred_housing_date', 'fred_housing', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_employment_date'), table_name='fred_employment')
    op.create_index('idx_fred_employment_date', 'fred_employment', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_economic_growth_date'), table_name='fred_economic_growth')
    op.create_index('idx_fred_economic_growth_date', 'fred_economic_growth', ['date'], unique=False)
    op.drop_index(op.f('ix_fred_consumer_business_date'), table_name='fred_consumer_business')
    op.create_index('idx_fred_consumer_business_date', 'fred_consumer_business', ['date'], unique=False)
    op.drop_index(op.f('ix_dji_prices_date'), table_name='dji_prices')
    op.create_unique_constraint('dji_prices_symbol_date_key', 'dji_prices', ['symbol', 'date'])
    op.alter_column('dji_prices', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('dji_prices', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('dji_prices', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('dji_prices', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('dji_prices', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('dji_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_table('feature_metrics')
    op.drop_table('features')
    op.drop_table('feature_compositions')
    # ### end Alembic commands ###
